import { BadRequestException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service'; import { AuditService } from '../audit/audit.service'; import { AuditAction } from '@prisma/client';
import { CreateAssessmentDto, SaveMarksDto } from './dto/grades.dto';
@Injectable() export class GradesService {
 constructor(private readonly prisma: PrismaService,private readonly audit:AuditService) {}
 async create(offeringId: string, dto: CreateAssessmentDto, actor?:string) { const offering=await this.prisma.academicOffering.findUnique({where:{id:offeringId}});if(!offering)throw new NotFoundException('Academic offering not found');if(actor)await this.ensureBranchAccess(actor,offering.branchId);const assessment=await this.prisma.assessment.create({ data: { academicOfferingId: offeringId, title: dto.title.trim(), assessmentType: dto.assessmentType, heldOn: new Date(dto.heldOn) } }); const org=await this.prisma.organization.findFirstOrThrow();await this.audit.record({organizationId:org.id,actorUserId:actor,action:AuditAction.CREATE,entityType:'Assessment',entityId:assessment.id,changes:{offeringId,title:dto.title}});return assessment; }
 async list(offeringId: string) { return this.prisma.assessment.findMany({ where: { academicOfferingId: offeringId }, include: { _count: { select: { marks: true } } }, orderBy: { heldOn: 'desc' } }); }
 async saveMarks(assessmentId: string, dto: SaveMarksDto, actor?:string) { const assessment = await this.prisma.assessment.findUnique({ where: { id: assessmentId }, include:{academicOffering:true} }); if (!assessment) throw new NotFoundException('Assessment not found'); if(actor)await this.ensureBranchAccess(actor,assessment.academicOffering.branchId); if (dto.marks.some(m => m.obtainedMarks > m.maximumMarks)) throw new BadRequestException('Obtained marks cannot exceed maximum marks'); await this.prisma.$transaction(dto.marks.map(m => this.prisma.studentAssessmentMark.upsert({ where: { assessmentId_studentId_subjectId: { assessmentId, studentId: m.studentId, subjectId: m.subjectId } }, update: { maximumMarks: m.maximumMarks, obtainedMarks: m.obtainedMarks }, create: { assessmentId, studentId: m.studentId, subjectId: m.subjectId, maximumMarks: m.maximumMarks, obtainedMarks: m.obtainedMarks } }))); return { saved: dto.marks.length }; }
 async history(studentId: string,actor?:string) { const student=await this.prisma.student.findUnique({where:{id:studentId}});if(!student)throw new NotFoundException('Student not found');if(actor)await this.ensureBranchAccess(actor,student.branchId); const marks = await this.prisma.studentAssessmentMark.findMany({ where: { studentId }, include: { assessment: true, subject: true }, orderBy: { assessment: { heldOn: 'desc' } } }); return marks.map(m => ({ ...m, percentage: Number(m.obtainedMarks) * 100 / Number(m.maximumMarks) })); }
 async ensureBranchAccess(userId:string,branchId:string){const a=await this.prisma.roleAssignment.findFirst({where:{userId,OR:[{branchId:null},{branchId}]}});if(!a)throw new ForbiddenException('You do not have access to this branch');}
}
